install:
	npm install @mui/material @emotion/react @emotion/styled
	npm install @mui/icons-material
	npm install react-google-charts
	npm install uuid


run:
	npm start


clean:
	rm -rf build


package:
	npm run build


build: clean package